name: Deploy to EC2

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd student-attendace
            git pull origin develop
            source venv/bin/activate
            pip install -r requirements.txt
            pkill -f gunicorn || true
            nohup gunicorn --bind 0.0.0.0:8000 atend.wsgi:application > log.txt 2>&1 &
